[package]
name = "flatten"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
git2 = "0.20.2"
tokio = { version = "1", features = ["full"] }
base64 = "0.22.1"
